# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Adding the generators here allows us to vendor the code-generator package
# This is required since code-generator is not directly or transitively
# dependent
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller"
  ]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.3"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.0"

[[override]]
  name = "github.com/kubernetes-sigs/sig-storage-lib-external-provisioner"
  version = "v1.0.0"

# Apply workaround from https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/jpillora/go-ogle-analytics"
  source = "github.com/openebs/go-ogle-analytics"
  revision = "694492144d734d1500dfb877b47fb2f32a4ec53f"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.3"
